package com.boardgamebrag.model;

// Generated Dec 29, 2013 3:45:25 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.*;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FeedbackTitle generated by hbm2java
 */
@Entity
@Table(name = "feedback_title", catalog = "boardgamebrag_dev")
public class FeedbackTitle implements Serializable {

    private Integer titleId;
    private String name;
    private Long enteredBy;
    private Date enteredDate;
    private Long changedBy;
    private Date changedDate;

    public FeedbackTitle() {
    }

    public FeedbackTitle(String name, Long enteredBy, Date enteredDate) {
        this.name = name;
        this.enteredBy = enteredBy;
        this.enteredDate = enteredDate;
    }

    public FeedbackTitle(String name, Long enteredBy, Date enteredDate, Long changedBy, Date changedDate) {
        this.name = name;
        this.enteredBy = enteredBy;
        this.enteredDate = enteredDate;
        this.changedBy = changedBy;
        this.changedDate = changedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "title_id", unique = true, nullable = false)
    public Integer getTitleId() {
        return this.titleId;
    }

    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    @Column(name = "name", nullable = false, length = 60)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "entered_by", nullable = false)
    public Long getEnteredBy() {
        return this.enteredBy;
    }

    public void setEnteredBy(Long enteredBy) {
        this.enteredBy = enteredBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "entered_date", nullable = false, length = 19)
    public Date getEnteredDate() {
        return this.enteredDate;
    }

    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }

    @Column(name = "changed_by")
    public Long getChangedBy() {
        return this.changedBy;
    }

    public void setChangedBy(Long changedBy) {
        this.changedBy = changedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "changed_date", length = 19)
    public Date getChangedDate() {
        return this.changedDate;
    }

    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }
}
