package com.boardgamebrag.model;

// Generated Dec 29, 2013 3:45:25 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.*;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.DynamicUpdate;

import com.boardgamebrag.util.UserMetaDataSaveEventListener;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "boardgamebrag_dev", uniqueConstraints = @UniqueConstraint(columnNames = "email_address"))
@EntityListeners(UserMetaDataSaveEventListener.class)
@DynamicUpdate
public class User implements Serializable, UserAuditMetaData {
    
    private static final Long serialVersionUID = -7512407588070720964L;
    
    private String password;
    
    /* Persisted */
    private Long userId;
    private String emailAddress;
    private String name;
    private Integer experience;
    private String passwordHash;
    private String passwordSalt;
    private String zipcode;
    private Long enteredBy;
    private Date enteredDate;
    private Long changedBy;
    @Version
    private Date changedDate;
    
    public User() {
    }
    
    @PrePersist
    public void beforeCreate() {
        this.enteredDate = new Date();
    }
    
    @PreUpdate
    public void beforeUpdate() {
        this.changedDate = new Date();
    }
    
    public User(String emailAddress, String name, String passwordHash, String passwordSalt, Long enteredBy, Date enteredDate) {
        this.emailAddress = emailAddress;
        this.name = name;
        this.passwordHash = passwordHash;
        this.passwordSalt = passwordSalt;
        this.enteredBy = enteredBy;
        this.enteredDate = enteredDate;
    }

    public User(String emailAddress, String name, Integer experience, String passwordHash, String passwordSalt, String zipcode, Long enteredBy, Date enteredDate, Long changedBy, Date changedDate) {
        this.emailAddress = emailAddress;
        this.name = name;
        this.experience = experience;
        this.passwordHash = passwordHash;
        this.passwordSalt = passwordSalt;
        this.zipcode = zipcode;
        this.enteredBy = enteredBy;
        this.enteredDate = enteredDate;
        this.changedBy = changedBy;
        this.changedDate = changedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "user_id", unique = true, nullable = false)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Column(name = "email_address", unique = true, nullable = false, length = 60)
    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    @Column(name = "name", nullable = false, length = 90)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "experience")
    public Integer getExperience() {
        return this.experience;
    }

    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    @Column(name = "password_hash", nullable = false, length = 45)
    public String getPasswordHash() {
        return this.passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    @Column(name = "password_salt", nullable = false, length = 45)
    public String getPasswordSalt() {
        return this.passwordSalt;
    }

    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    @Column(name = "zipcode", length = 10)
    public String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    @Column(name = "entered_by", nullable = false)
    public Long getEnteredBy() {
        return this.enteredBy;
    }

    public void setEnteredBy(Long enteredBy) {
        this.enteredBy = enteredBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "entered_date", nullable = false, length = 19)
    public Date getEnteredDate() {
        return this.enteredDate;
    }

    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }

    @Column(name = "changed_by")
    public Long getChangedBy() {
        return this.changedBy;
    }

    public void setChangedBy(Long changedBy) {
        this.changedBy = changedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "changed_date", length = 19)
    public Date getChangedDate() {
        return this.changedDate;
    }

    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    @Transient
    public String getPassword() {
        return this.password;
    }
}
